name: Video Editor Workflow

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Video URL'
        required: true
        type: string
      audio_url:
        description: 'Audio URL'
        required: false
        type: string
      video_title:
        description: 'Video Title Prefix'
        required: true
        type: string
      game_name:
        description: 'Game Name'
        required: true
        type: string
      ratio:
        description: 'Crop Ratio'
        required: true
        type: string
      filter:
        description: 'Color Filter'
        required: true
        type: string
      speed:
        description: 'Video Speed'
        required: true
        type: string
      clip_count:
        description: 'Clip Count'
        required: true
        type: string
      clip_len:
        description: 'Clip Length'
        required: true
        type: string
      fps:
        description: 'FPS'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: echo "Running workflow for ${{ github.event.inputs.video_url }}"
